-- VIEWS
    -- CREATE VIEW
    CREATE VIEW full_reviews AS 
    SELECT s.TITLE, s.RELEASED_YEAR, s.GENRE, r.RATING, re.FIRST_NAME, re.LAST_NAME
    FROM REVIEWS r 
    JOIN SERIES s ON s.id = r.SERIE_ID
    JOIN REVIEWERS re ON re.ID = r.reviewer_ID;

    CREATE VIEW ordered_series AS
    SELECT* FROM SERIES
    ORDER BY RELEASED_YEAR;

    -- UPDATE VIEWS
    INSERT INTO ORDERED_SERIES(TITLE, RELEASED_YEAR, GENRE)
    VALUES('The Great', 2020, 'Comedy');

    -- REPLACE VIEW
    CREATE OR REPLACE VIEW ordered_series AS
    SELECT* FROM SERIES
    ORDER BY RELEASED_YEAR DESC;

    -- DELETE VIEW
    DROP VIEW ORDERED_SERIES;

    -- HAVING
    SELECT TITLE, avg(RATING), count(rating) as Review_Count
    FROM FULL_REVIEWS
    GROUP BY TITLE
    HAVING count(RATING) > 1;

    -- WITH ROLLUP
    SELECT TITLE, avg(RATING), count(rating) as Review_Count
    FROM FULL_REVIEWS
    GROUP BY TITLE
    HAVING count(RATING) > 1;

    SELECT TITLE, AVG(RATING) 
    FROM FULL_REVIEWS
    GROUP BY TITLE WITH ROLLUP;

    SELECT RELEASED_YEAR, GENRE, AVG(RATING)
    FROM FULL_REVIEWS
    GROUP BY RELEASED_YEAR, GENRE WITH ROLLUP;

-- MODES
    -- To View Modes:
    SELECT @@GLOBAL.sql_mode;
    SELECT @@SESSION.sql_mode;
    
    -- To Set Them:
    SET GLOBAL sql_mode = 'modes';
    SET SESSION sql_mode = 'modes';