-- VIEWS
    -- CREATE VIEW
    CREATE VIEW full_reviews AS 
    SELECT s.TITLE, s.RELEASED_YEAR, s.GENRE, r.RATING, re.FIRST_NAME, re.LAST_NAME
    FROM REVIEWS r 
    JOIN SERIES s ON s.id = r.SERIE_ID
    JOIN REVIEWERS re ON re.ID = r.reviewer_ID;

    CREATE VIEW ordered_series AS
    SELECT* FROM SERIES
    ORDER BY RELEASED_YEAR;

    -- UPDATE VIEWS
    INSERT INTO ORDERED_SERIES(TITLE, RELEASED_YEAR, GENRE)
    VALUES('The Great', 2020, 'Comedy');

    -- REPLACE VIEW
    CREATE OR REPLACE VIEW ordered_series AS
    SELECT* FROM SERIES
    ORDER BY RELEASED_YEAR DESC;

    -- DELETE VIEW
    DROP VIEW ORDERED_SERIES;